[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "frontend"
buildCommand = "npm run build"
startCommand = "npm start"
